// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "description": "Возвращает 200 пока процесс жив",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "description": "Возвращает 200 когда сервис готов принимать трафик",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "shutting down | queue is not being processed",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/tasks": {
            "post": {
                "description": "Принимает сжатый маршрут, ставит задачу в очередь, сразу отдаёт taskKey. Обработка — в фоне; результат забирать по taskKey.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Сдать маршрут в очередь на очистку",
                "parameters": [
                    {
                        "description": "Маршрут для обработки",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.SubmitRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/api.SubmitResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorPayload"
                        }
                    }
                }
            }
        },
        "/v1/tasks/{taskKey}": {
            "get": {
                "description": "По taskKey возвращает статус (pending/done/failed); при done — очищенный маршрут и длину, при failed — текст ошибки.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Статус и результат задачи",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ключ задачи (из submit)",
                        "name": "taskKey",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.StatusResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorPayload"
                        }
                    }
                }
            }
        },
        "/v1/tasks/{taskKey}/debug": {
            "get": {
                "description": "По taskKey возвращает статистику по каждой стадии очистки (заполнена при done).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Разбор задачи по стадиям pipeline",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ключ задачи (из submit)",
                        "name": "taskKey",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.DebugResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorPayload"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.DebugResponse": {
            "type": "object",
            "properties": {
                "debug": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pipeline.StageStats"
                    }
                },
                "status": {
                    "type": "string"
                },
                "taskKey": {
                    "type": "string"
                }
            }
        },
        "api.ErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "api.ErrorPayload": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/api.ErrorBody"
                }
            }
        },
        "api.StatusResponse": {
            "type": "object",
            "properties": {
                "degraded": {
                    "description": "Километражу верить с оговоркой: часть дыр осталась прямыми через поля.",
                    "type": "boolean"
                },
                "error": {
                    "type": "string"
                },
                "lengthMeters": {
                    "type": "number"
                },
                "routeCompressed": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "taskKey": {
                    "type": "string"
                },
                "warnings": {
                    "description": "Та же оговорка словами, для человека при разборе.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "api.SubmitRequest": {
            "type": "object",
            "properties": {
                "routeCompressed": {
                    "type": "string"
                }
            }
        },
        "api.SubmitResponse": {
            "type": "object",
            "properties": {
                "taskKey": {
                    "type": "string"
                }
            }
        },
        "pipeline.StageStats": {
            "type": "object",
            "properties": {
                "elapsed": {
                    "type": "string",
                    "example": "47.123ms"
                },
                "error": {
                    "description": "Error — причина, по которой стадия упала. Пустая, если всё хорошо.",
                    "type": "string"
                },
                "extra": {
                    "description": "Extra — подробности стадии для разбора спорных маршрутов.\n\nПо числу точек до и после ничего не понять: ядро может выбросить\nполовину трека и быть правым, а может ошибиться на одном правиле.\nЗдесь лежит то, что об этом говорит: сколько дыр нашла дорисовка,\nсколько проходов сделало ядро, сколько точек вернул страж.",
                    "type": "object",
                    "additionalProperties": {}
                },
                "name": {
                    "type": "string",
                    "example": "collapse_stops"
                },
                "pointsAfter": {
                    "type": "integer",
                    "example": 2981
                },
                "pointsBefore": {
                    "type": "integer",
                    "example": 3016
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Ariadne API",
	Description:      "Сервис устранения коллизий GPS-маршрутов",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
