// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "description": "Возвращает 200 пока процесс жив",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "description": "Возвращает 200 когда сервис готов принимать трафик",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/routes/resolve-collisions": {
            "post": {
                "description": "Принимает сжатый маршрут, прогоняет через pipeline (sort, speed filter, dedup, intersections), возвращает очищенный результат",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "routes"
                ],
                "summary": "Устранение коллизий GPS-маршрута",
                "parameters": [
                    {
                        "description": "Маршрут для обработки",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ResolveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ResolveResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorPayload"
                        }
                    },
                    "413": {
                        "description": "Request Entity Too Large",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorPayload"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorPayload"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorPayload"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "api.ErrorPayload": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/api.ErrorBody"
                }
            }
        },
        "api.ResolveRequest": {
            "type": "object",
            "properties": {
                "returnDebug": {
                    "type": "boolean",
                    "example": false
                },
                "routeCompressed": {
                    "type": "string",
                    "example": "eJy..."
                }
            }
        },
        "api.ResolveResponse": {
            "type": "object",
            "properties": {
                "debug": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pipeline.StageStats"
                    }
                },
                "lengthBeforeMeters": {
                    "type": "number",
                    "example": 1170260.79
                },
                "lengthMeters": {
                    "type": "number",
                    "example": 1168113.85
                },
                "pointsCount": {
                    "type": "integer",
                    "example": 2981
                },
                "removedPointsCount": {
                    "type": "integer",
                    "example": 35
                },
                "routeCompressed": {
                    "type": "string",
                    "example": "eJy..."
                },
                "warnings": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "intersect: max iterations reached"
                    ]
                }
            }
        },
        "pipeline.StageStats": {
            "type": "object",
            "properties": {
                "elapsed": {
                    "type": "string",
                    "example": "47.123ms"
                },
                "name": {
                    "type": "string",
                    "example": "RemoveSelfIntersections"
                },
                "pointsAfter": {
                    "type": "integer",
                    "example": 2981
                },
                "pointsBefore": {
                    "type": "integer",
                    "example": 3016
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Ariadne API",
	Description:      "Сервис устранения коллизий GPS-маршрутов",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
